# Project info
site_name: The Developer's Guide to Saxo's OpenAPI
site_description: "The #1 reference for developers working with Saxo Bank's OpenAPI."
site_author: Saxo Bank A/S
copyright: 'Copyright &copy; 2020 Saxo Bank A/S'

# MkDocs config
theme:
  name: 'material'
  language: 'en'
  direction: 'ltr'
  palette:
    primary: 'blue'
    accent: 'black'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  logo:
    icon: 'school'
  feature:
    tabs: true

# Documentation structure
nav:
  - Home:
    - Welcome: index.md
    - Using the Guide: usage.md
    - Useful Tools: tools.md
    - Requesting Support: support.md
    - Disclaimer: disclaimer.md
  - The Basics:
    - Introduction: basics/index.md
    - Core Business Concepts:
      - Overview: basics/core-business-concepts/index.md
    - Fundamental Programming Concepts:
      - Overview: basics/fundamental-programming-concepts/index.md
    - Frequently Asked Questions:
      - FAQ Guide: basics/faq/index.md
      - How do I authenticate?: basics/faq/authentication.md
  - Individual Developers:
    - Introduction: individual/index.md
  - Institutional Developers:
    - Introduction: institutional/index.md
  - 3rd-Party App Developers:
    - Introduction: third-party/index.md
  - Updates:
    - Overview: updates/index.md
    - Planned Changes: updates/changes.md
    - Release Notes:
      - Guide: updates/release-notes/index.md
      - 2019-12-13 - Breaking: updates/release-notes/2019-12-13.md
      - "2019-11-25": updates/release-notes/2019-11-25.md
      - "2019-09-03": updates/release-notes/2019-09-03.md

# Required extensions
markdown_extensions:
  - admonition
  - pymdownx.extra
  - pymdownx.details
  - attr_list
  - codehilite:
      linenums: true

extra:
  social:
    - type: 'github'
      link: 'https://github.com/SaxoBank'
    - type: 'twitter'
      link: 'https://twitter.com/saxobank'
    - type: 'linkedin'
      link: 'https://www.linkedin.com/company/saxo-bank/'