site_name: The Developer's Guide to Saxo's OpenAPI

theme:
  name: 'material'
  language: 'en'
  palette:
    primary: 'black'
    accent: 'indigo'
  font:
    text: 'Ubuntu'
    code: 'Ubuntu Mono'
# logo: 'images/saxo_logo.svg'    this requies additional CSS to properly style the logo in the header bar
  logo:
    icon: 'school'
#  favicon: 'school'   this would have to be replaced by Saxo logo too at some point